---
title: "1.The Data Scientist's Toolbox"
output: rmarkdown::github_document
---
> ### 1. What Is Data Science?

* Data Science란 데이터를 사용해 질문에 답하는 분야로 통계학, 컴퓨터 과학, 수학, 데이터 클리닝, 시각화가 포함된다. 
* Data Science가 구현하는 기술 3종류:
  + 전문 지식 
  + 컴퓨터 프로그래밍
  + 수학&통계 지식  
* Data Science Project 분석 순서:
  + 질문 형성 
  + 해당 질문에 답하는데 사용할 데이터를 찾거나 생성
  + 데이터를 탐색한 다음 데이터를 모델링하여 데이터를 분석 (통계 또는 기계학습)하고 질문에 대한 답을 도출
  + 결론을 도출한 후 프로젝트를 다른 사람에게 전달 (상사나 팀에 보내는 보고서)
* Data Scientist란 데이터의 산 속에 숨겨진 금덩어리를 추출하는 사람이다.    
<br>    
                
> ### 2. Github & RStudio

* [Github](https://github.com/)란 버전 제어 파일을 위한 클라우드 기반 관리 시스템으로 DropBox와 마찬가지로 파일은 컴퓨터에 로컬로 저장되며 온라인에서 호스팅되기 때문에 쉽게 액세스할 수 있다. 
* Github 관련 알아야 할 용어 
  + Repository: 프로젝트 폴더 또는 디렉토리로 모든 버전 제어 파일과 기록된 변경 사항은 Repository에 남아 있음
  + Commit: 편집 내용과 변경 내용을 저장한 것으로 오류가 발생하면 파일을 이전 Commit으로 되돌린다.
  + Push: 편집 내용으로 Repository를 업데이트 하는 것
  + Pull: 다른 Repository 버전이 동시에 편집되었을 수 있으므로 가져오기를 통해 Repository의 로컬 버전을 현재 버전으로 업데이트  

* Github와 RStudio 연동하는 방법 
  + Git 다운로드 및 계정 생성
    + Git 다운로드 후 Git Bash 실행
    + git config --global user.name 'Dohyun Park' 입력
    + git config --global user.email sallys93@naver.com 입력
    + git config --list 입력하여 확인
  + Rstudio & Github 옵션 설정
    + Tools -> Global options -> Git/SVN 
    + Git executable 경로 확인 후 Create RSA Key 눌러서 키 생성
    + View public key 클릭한 후 키 복사 
    + Github Page -> SSH and GPG keys 카테고리 클릭
    + New SSH key -> Title 설정 후 Key 칸에 복사한 키 붙여넣기
    + Add SSH key 클릭
  + RStudio에서 바로 Github에 Push 하는 방법
    + File -> New Project -> Version Control -> Git
    + 연동할 Github repository URL 입력 & 폴더 저장할 위치 설정
    + 코드 작성 후 오른쪽 상단의 Git 탭 클릭 
    + Staging할 항목 선택 -> Commit 클릭 
    + Commit 멘트 작성 -> Commit 클릭 -> Push 클릭   
<br>    
    
> ### 3. Types Of Data Science Questions

* 데이터 분석의 첫 단계는 '문제 정의'이다. 문제 정의를 통해 목표를 구체적으로 설정하고 문제 유형을 파악하여 어떤 분석 방법을 사용할 것인지 결정해야 한다.

* 일반적으로 데이터 분석이 속하는 6가지 범주는 아래와 같다.
  + Descriptive(설명)
  + Exploratory(탐색)
  + Inferential(추론)
  + Predictive(예측)
  + Causal(인과관계)
  + Mechanistic(기계적)
  
* Descriptive analysis  
가장 기본이 되는 분석으로, 주어진 데이터를 요약/집계하여 결과를 도출하는 것이 Descriptive analysis의 목표가 된다. Descriptive analysis는 단순 산/집계하여 얻어진 Fact이기 때문에, 분석 결과를 따로 해석하는 과정을 거치지 않는다. 대표적인 예로는 Pie chart, Box plot, Bar plot 등이 있으며, 요약 형식의 테이블도 이러한 유형의 분석의 결과물이다. 

* Exploratory analysis  
EDA라고도 불리우는 Exploratory analysis의 주요 목표는 여러 변수 간 트렌드나 패턴 혹은 관계를 찾는 것인데, 주로 데이터 분석 프로젝트 초기에 가설을 수립하기 위해 수행되기도 한다.

* Inferential analysis  
샘플과 모집단 간의 관계를 탐구하는 것이 이 분석의 목표이다. 샘플에서 얻어낸 정보가 모집단에도 적용될 수 있는지를 검토하는 것인데, 시간과 자원이 한정되어 있어 sample 크기를 무한정 늘릴 수 없기 때문에 발생하는 일반적인 문제를 해결하기 위한 분석의 유형이다. 

* Predictive analysis  
머신러닝, 의사결정나무와 같은 다양한 통계적 기법을 사용하여 미래 혹은 발생하지 않은 어떤 사건에 대한 예측을 하는 것이 목표이다. "왜" 보다는 "정확한 예측"을 하는 것이 주요 관심사이기 때문에, 특정한 설명변수가 어떤 매커니즘으로 타겟변수에 영향을 미치는가에 대한 설명력은 약하다. 최근 Predictive analysis에서 좀 더 나아간 Prescriptive analysis도 추목 받고 있는데, 이 유형의 분석은 어떤 의사결정을 하느냐에 따라 변하는 결과를 예측해주기 때문에 이러한 분석을 통해 최적화된 의사결정을 할 수 있다. 

* Causal analysis  
독립변수와 종속변수 간의 인과관계가 있는지 여부를 확인하기 위한 분석이다. Causal analysis의 특징 중 하나는 실험을 통해 수집된 데이터를 대상으로 한다는 점이다. 주로 독립변수를 실험대상에 랜덤하게 할당한 후, 그룹 간 실험 전/후의 종속변수의 변화를 관찰하여 실험 데이터 수집이 이루어진다. 과거의 Observational data로는 Confounding variable이 있을 가능성을 배제할 수가 없으므로, 인과관계 여부를 명확하게 밝혀 낼 수가 없기 때문이다. 대표적인 예로는 A/B test, linear regression등 이 있다. 

* Mechanistic analysis  
독립변수가 어떤 메커니즘으로 종속변수에 영향을 미치는지를 분석하는 것으로, 위 6가지 유형 중 가장 노력이 많이 필요한 분석 유형이다. Causal analysis의 목적이 독립-종속 변수간의 인과관계 여부를 밝혀내는 것이었다면, Mechanistic analysis의 목적은 이에 더해 어떤한 독립변수가 어떤한 작용을 통해 독립변수에 그러한 영향을 미치는지를 이해하는 것이다. Causal analysis와 동일하게 실험 데이터를 분석대상으로 한다. 
<br>

> ### 4. Experimental Design

* 실험 설계는 Data Science 질문에 명확하고 효과적으로 답할 수 있는 올바른 데이터를 갖도록 실험을 구성한다. 이 프로세스에는 데이터 수집에 앞서 질문을 명확하게 공식화하고, 질문에 답하기 위해 데이터를 수집할 수 있는 최상의 설정을 설계한다. 또한, 설계의 문제 또는 오류 원인을 식별하며 적절한 데이터를 수집하는 것이 포함된다. 

* 실험 설계의 원리
실험 설계에는 많은 개념과 용어가 내재되어 있는데 자세한 내용은 아래와 같다.  
  + 독립변수 (Independent variable): 실험자가 조작하는 변수로 측정된느 다른 변수에 의존하지 않는다.
  + 종속변수 (Dependent variable): 독립변수의 변화로 인해 변화될 것으로 예상되는 변수.
  + 교란작용 (Confounder): 종속변수와 독립변수 간의 관계에 영향을 줄 수 있는 외부 변수. 교랸작용을 제거하기 위해 방법으로 각 그룹에 개인을 Randomization 할당하거나 Propensity Score Matching이 있다.  
  + 대조군 (Control group): 어떤 조작이나 조건도 가하지 않은 집단.
  + 치료군 (Treatment group): 인위적으로 어떤 조작이나 조건을 가한 집단.
  
* 따라서 실험을 설계할 때 독립변수와 종속변수를 설정해야 하며. 가설을 설정해야 한다.
<br>



    
    
    
